### ISSUE TITLE
API Key stored in NSUserDefaults

### ISSUE THREAD

**Issue by joshpc** [haawa799/WaniKani-iOS#1]
## Problem

WaniKani's API Key stored in NSUserDefaults.

**WaniApiManager.swift: 48**

```
  public func setApiKey(key: String) {
    NSUserDefaults.standardUserDefaults().setObject(key, forKey: WaniApiManager.userDefaulsKey)
    NSUserDefaults.standardUserDefaults().synchronize()
    myKey = key
  }
```

API Keys are considered sensitive materials (they're really a gateway to your account) and should be treated as such. They should be stored in the user's secure keychain instead of user defaults (which is just stored in plaintext as a plist, last I checked?).
## Comments

Thanks for the app! I started using it for notifications and enjoy receiving them this way. I was going to fork this and fix this for you but I can't run the app locally anymore because of Fabric. It looks like you pulled in Fabric for crash reporting, but is it possible to pull that in without needing every dev to log in?

**Comment by haawa799** [comment]
Fixed in the last commit
