### ISSUE TITLE
How to know the bezier path data of character

### ISSUE THREAD

**Issue by xmliteworkltd** [haawa799/WaniKani-iOS#4]
I’m very glad to see the project on the Github of yours. I download the project, and It is work well. But how can you get bezier path data of every 

Chinese character and save to the db. Rencently ,I will make an app that is similar to yours, the main function is stroke order animation. I really need 

you help and thanks a lot!

**Comment by haawa799** [comment]
I gave you some info on that via email. If you have some more questions feel free to ask!
